name: 'Playground'
description: 'A GitHub Action to run a playground script'
author: 'Oleksii Kryvtsov'

inputs:
  script:
    description: 'The script to run in the playground'
    required: true
    default: 'some-script'

outputs:
  result:
    description: 'The result of the playground script'

runs:
  using: 'node20'
  main: 'dist/index.js'
