name: 'Libs playground'

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        script: 'playground'
      id: result
    - run: echo ${{ steps.result.outputs.result }}
